### PR TITLE
Finish conversion, and fix compile errors.

### PR DESCRIPTION
**Pull request by Tetragramm**
Doesn't run though.  "Uncaught ReferenceError: System is not defined"
Getting it from the typescript to the working javascript is where I have problems.

### CODE REVIEW

**Comment by Tetragramm** [comment]
Okay, I think it's actually working.  I moved the ts files into the /ts folder, because having them side-by-side with the js files is painful to navigate.

**Comment by Tetragramm** [comment]
Give it a look and see if it's actually what you need out of the modules.

**Comment by Darkade** [comment]
I'll check it out later today! In the meantime I basically moved the `InteractiveDash` `InteractiveEngines` and `InteractiveWeapons` from `disp/Airplane` into `impl/Airplane`  and it sort of works!!

However there's still `WeaponName`, `WeaponTags` being imported from `disp/Weapons` I'll check on those functions dependencies, but maybe they should be elsewhere.

I'm also thinking of declaring a module with some global-ish functions, for example `engine_list` which right now I'm very hackishly copying and pasting wherever it's needed

https://github.com/Tetragramm/Tetragramm.github.io/issues/4

**Comment by Tetragramm** [comment]
If you look at the pull request, I moved engine_list to it's own module, with a module-local variable, and accessor functions.
impl/EngineList.ts
GetEngineLists()
GetEngineJSON()
And did the same with Localization.

**Comment by Darkade** [comment]
Nice! I'm checking it and integrating then :3

**Comment by Darkade** [comment]
I'll be working in this branch https://github.com/Darkade/Tetragramm.github.io/tree/feature/modulemigration

Right now I'm getting again the plane derived stats from `saveInteractive` so the basic-full-flow is working

Separating everything into the ts folder was very useful.

I think the next commit will be regarding all the jsons. In `tsconfig.json` you can add this option `"resolveJsonModule": true,` that allows the import of jsons as modules. And using Webpack those jsons could be easily integrated without promises

for example importing `engines.json` could be done as `import { engine_JSON } from "../../engines.json";`

**Comment by Darkade** [comment]
And the `server.py` seems to be working in a very limited test. So 👍🏽

**Pull request merged**
